### PR TITLE
allow files to control filters with a CMake comment

### PR DESCRIPTION
**Pull request by wjwwood**
Now you can add a filter, which is only for the current file, using a comment which starts with `# lint_cmake: ` and is followed with a list of filters, separated by commas.

Example:

```cmake
...
# Suppress linter warnings about FindPackageHandleStandardArgs and file name.
# lint_cmake: -package/consistency, -convention/filename
...
```

### CODE REVIEW

**Comment by richq** [comment]
Thanks for this, I'll take a look at these 2 in detail tonight.

**Comment by richq** [comment]
Merged this one too. I moved the code around a bit to make it testable, should still function the same way though.

**Comment by dirk-thomas** [comment]
I just ran into this "feature". My CMake file has a comment line which looks like this:

    # lint_cmake: the next line does not follow the style guide to check that the linter detects this

While such a comment is very uncommon it might be better to only warn about it (if the pragma can't be parsed) but continue processing the file. My simple work around for now will be to slightly modify the comment to look like a pragma.

**Comment by richq** [comment]
Well that sucks. I've opened issue #11 to track it.

**Pull request merged**
